Add Index & CSS
hasenat-eqbali/code-review-project pull request #1
Opened 2023-01-17 08:43 UTC by hasenat-eqbali

I have added index file with css in the project.

2023-01-17 08:46 UTC, hasenat-eqbali commented
Required Changes ♻️

- Add Linter so you can check the errors.
- Add Read me file with a good description.
Thank You!

2023-01-17 09:00 UTC, IngDavidTM requested changes
## Hi @hasenat-eqbali  🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- Comments are polite ✅ 
- The Pull Request uses "Review changes"

## Suggested changes

- [ ] You did an amazing job reviewing the code :+1:, but as a requirement, you should add at least one comment using [GitHub inline comments feature](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request)

- [ ] I think it would be better if your comments always include an explanation to help the student understand what you mean :+1:. You can check more about it [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md#how-to-communicate)

- [ ] Finally, as a requirement you should phrase the comments politely, as suggestions instead of orders.
  - This is a polite suggestion: *"I think it would be better to add the README file..."*
  - This reads as an order: *"Add Read me file with a good description."*

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 09:57 UTC, TuyishimireEric requested changes
# Status: REQUIRED CHANGES :recycle: 
### Hi  @hasenat-eqbali   👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far 👍 
 there are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Highlights 
✔ Professional PR

## Required Changes ♻️

- [ ] **As suggested by the previous reviewer**, think it would be better to use the [GitHub inline comments feature](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) at least once to leave review comments. 👍 

- [ ]  As suggested by the previous reviewer, It would be better also to always include an explanation, a "why", for each requested change to make it clear to the code writer 😍😎

## Optional request 
- [ ] **[Optional]** I think It would be better to use a couple of emojis or gifs in the review to make the code review more human-friendly 👽😍

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 04:04 UTC, Shedrack-Sunday requested changes
Hi @hasenat-eqbali 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


Required Changes ♻️

- [ ] Just as the previous reviews mentioned, you're meant to use inline comments to give a review, which should at least be two. the one you did happens to be a summary. Please check the [How to give a code review](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md) Section to see how this is done.  I've also included a screenshot from the guide to show you how. check them below 👍 

![image](https://user-images.githubusercontent.com/50990925/213080906-87633c7c-7f77-4a8e-a988-3d43fa56d654.png)


Check the comments under the review.

 I think you forgot to complete your two inline comments, I would advise you to always complete your comments so that the student can well understand your comment.
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-18 05:25 UTC, hasenat-eqbali reviewed
Required changes 🧩

Please review the comments below. 

Thanks and happy coding.

2023-01-18 05:25 UTC, hasenat-eqbali commented on index.html
> -
Please use html5 structure to start your project. html5 is the latest version of HTML, and it makes your code more readable for the browser. it supports other languages as well.

2023-01-18 05:25 UTC, hasenat-eqbali commented on index.html
> +
Kindly, remove extra blank lines and format your code like a pro. it makes your code more readable and easy to understand for review and debugging.

2023-01-18 05:36 UTC, amejid approved these changes
Hi @hasenat-eqbali, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Good use of Github features :heavy_check_mark: 
- Comments are polite :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 05:42 UTC, merged